<?php 
function facebook_emoticon($text)
{
    preg_match_all ('#<span class="facebook_emoticon (.+?)" emoticon_data="(.+?)"></span>#', facebook_emoticon_list(), $emoticons);
    foreach ($emoticons[2] as $key => $value)
	{
		$replaces[$value] = '<span class="facebook_emoticon '.$emoticons[1][$key].'" emoticon_data="'.$value.'"></span>';
	}
	$regex  = '/([0-9#][\x{20E3}])|[\x{00ae}\x{00a9}\x{203C}\x{2047}\x{2048}\x{2049}\x{3030}\x{303D}\x{2139}\x{2122}\x{3297}\x{3299}][\x{FE00}-\x{FEFF}]?|[\x{2190}-\x{21FF}][\x{FE00}-\x{FEFF}]?|[\x{2300}-\x{23FF}][\x{FE00}-\x{FEFF}]?|[\x{2460}-\x{24FF}][\x{FE00}-\x{FEFF}]?|[\x{25A0}-\x{25FF}][\x{FE00}-\x{FEFF}]?|[\x{2600}-\x{27BF}][\x{FE00}-\x{FEFF}]?|[\x{2900}-\x{297F}][\x{FE00}-\x{FEFF}]?|[\x{2B00}-\x{2BF0}][\x{FE00}-\x{FEFF}]?|[\x{1F000}-\x{1F6FF}][\x{FE00}-\x{FEFF}]?/u';
	$output = preg_replace_callback($regex,function($m) use ($replaces)
	{
		if(isset($replaces[$m[0]]))
		{
			return $replaces[$m[0]];
		}
		else
		{
			return $m[0];
		}
	},$text);
	return $output;
}


function facebook_emoticon_list()
{
	$emoticon_list = 
    '
    	// Smileys And People
		<span class="facebook_emoticon agoenks29D_kmi5s" emoticon_data="😀"></span>
		<span class="facebook_emoticon agoenks29D_wykb1" emoticon_data="😬"></span>
		<span class="facebook_emoticon agoenks29D_k6eg1" emoticon_data="😁"></span>
		<span class="facebook_emoticon agoenks29D_3ny4d" emoticon_data="😂"></span>
		<span class="facebook_emoticon agoenks29D_vlnj7" emoticon_data="😃"></span>
		<span class="facebook_emoticon agoenks29D_dicla" emoticon_data="😅"></span>
		<span class="facebook_emoticon agoenks29D_v87wj" emoticon_data="😆"></span>
		<span class="facebook_emoticon agoenks29D_5gmp0" emoticon_data="😇"></span>
		<span class="facebook_emoticon agoenks29D_9b2h3" emoticon_data="😉"></span>
		<span class="facebook_emoticon agoenks29D_o63pm" emoticon_data="😊"></span>
		<span class="facebook_emoticon agoenks29D_ifezv" emoticon_data="🙂"></span>
		<span class="facebook_emoticon agoenks29D_u8aoz" emoticon_data="☺"></span>
		<span class="facebook_emoticon agoenks29D_1mfdh" emoticon_data="😋"></span>
		<span class="facebook_emoticon agoenks29D_vju8r" emoticon_data="😌"></span>
		<span class="facebook_emoticon agoenks29D_kvyxi" emoticon_data="😍"></span>
		<span class="facebook_emoticon agoenks29D_0jsed" emoticon_data="😘"></span>
		<span class="facebook_emoticon agoenks29D_l0gas" emoticon_data="😚"></span>
		<span class="facebook_emoticon agoenks29D_9ikrn" emoticon_data="😜"></span>
		<span class="facebook_emoticon agoenks29D_jiw6k" emoticon_data="😝"></span>
		<span class="facebook_emoticon agoenks29D_di479" emoticon_data="😛"></span>
		<span class="facebook_emoticon agoenks29D_tu07c" emoticon_data="😎"></span>
		<span class="facebook_emoticon agoenks29D_2j7n0" emoticon_data="😏"></span>
		<span class="facebook_emoticon agoenks29D_5te17" emoticon_data="😶"></span>
		<span class="facebook_emoticon agoenks29D_zm5rs" emoticon_data="😐"></span>
		<span class="facebook_emoticon agoenks29D_w16pa" emoticon_data="😑"></span>
		<span class="facebook_emoticon agoenks29D_126gq" emoticon_data="😒"></span>
		<span class="facebook_emoticon agoenks29D_oqaid" emoticon_data="😳"></span>
		<span class="facebook_emoticon agoenks29D_bsqdr" emoticon_data="😞"></span>
		<span class="facebook_emoticon agoenks29D_4wdeu" emoticon_data="😟"></span>
		<span class="facebook_emoticon agoenks29D_j54f6" emoticon_data="😠"></span>
		<span class="facebook_emoticon agoenks29D_gi76y" emoticon_data="😡"></span>
		<span class="facebook_emoticon agoenks29D_3o94f" emoticon_data="😔"></span>
		<span class="facebook_emoticon agoenks29D_lp0ai" emoticon_data="😕"></span>
		<span class="facebook_emoticon agoenks29D_mg3cp" emoticon_data="😣"></span>
		<span class="facebook_emoticon agoenks29D_61eub" emoticon_data="😖"></span>
		<span class="facebook_emoticon agoenks29D_zw6l9" emoticon_data="😫"></span>
		<span class="facebook_emoticon agoenks29D_gar9f" emoticon_data="😩"></span>
		<span class="facebook_emoticon agoenks29D_o35mw" emoticon_data="😤"></span>
		<span class="facebook_emoticon agoenks29D_xa3nd" emoticon_data="😮"></span>
		<span class="facebook_emoticon agoenks29D_er9m2" emoticon_data="😱"></span>
		<span class="facebook_emoticon agoenks29D_93wmo" emoticon_data="😨"></span>
		<span class="facebook_emoticon agoenks29D_16cm9" emoticon_data="😰"></span>
		<span class="facebook_emoticon agoenks29D_25xps" emoticon_data="😯"></span>
		<span class="facebook_emoticon agoenks29D_shpyg" emoticon_data="😧"></span>
		<span class="facebook_emoticon agoenks29D_bciwo" emoticon_data="😥"></span>
		<span class="facebook_emoticon agoenks29D_a8o6k" emoticon_data="😢"></span>
		<span class="facebook_emoticon agoenks29D_1ybxn" emoticon_data="😪"></span>
		<span class="facebook_emoticon agoenks29D_lkfvr" emoticon_data="😓"></span>
		<span class="facebook_emoticon agoenks29D_d7rc9" emoticon_data="😭"></span>
		<span class="facebook_emoticon agoenks29D_2vt30" emoticon_data="😵"></span>
		<span class="facebook_emoticon agoenks29D_p8d65" emoticon_data="😲"></span>
		<span class="facebook_emoticon agoenks29D_ieqtc" emoticon_data="😷"></span>
		<span class="facebook_emoticon agoenks29D_z6l19" emoticon_data="😴"></span>
		<span class="facebook_emoticon agoenks29D_pou73" emoticon_data="💤"></span>
		<span class="facebook_emoticon agoenks29D_j8t1n" emoticon_data="💩"></span>
		<span class="facebook_emoticon agoenks29D_8xhg5" emoticon_data="😈"></span>
		<span class="facebook_emoticon agoenks29D_ipkvj" emoticon_data="👿"></span>
		<span class="facebook_emoticon agoenks29D_g19i6" emoticon_data="👹"></span>
		<span class="facebook_emoticon agoenks29D_hevpg" emoticon_data="👺"></span>
		<span class="facebook_emoticon agoenks29D_7spfi" emoticon_data="💀"></span>
		<span class="facebook_emoticon agoenks29D_q5dgo" emoticon_data="👻"></span>
		<span class="facebook_emoticon agoenks29D_l5ds0" emoticon_data="👽"></span>
		<span class="facebook_emoticon agoenks29D_7aibj" emoticon_data="😺"></span>
		<span class="facebook_emoticon agoenks29D_dmak8" emoticon_data="😹"></span>
		<span class="facebook_emoticon agoenks29D_i37uh" emoticon_data="😻"></span>
		<span class="facebook_emoticon agoenks29D_c7ye4" emoticon_data="😼"></span>
		<span class="facebook_emoticon agoenks29D_6i01y" emoticon_data="😽"></span>
		<span class="facebook_emoticon agoenks29D_r12pq" emoticon_data="😿"></span>
		<span class="facebook_emoticon agoenks29D_afbvo" emoticon_data="👏"></span>
		<span class="facebook_emoticon agoenks29D_zauct" emoticon_data="👋"></span>
		<span class="facebook_emoticon agoenks29D_fshm9" emoticon_data="👍"></span>
		<span class="facebook_emoticon agoenks29D_8i5nd" emoticon_data="👎"></span>
		<span class="facebook_emoticon agoenks29D_un6ls" emoticon_data="👊"></span>
		<span class="facebook_emoticon agoenks29D_jzo6i" emoticon_data="✊"></span>
		<span class="facebook_emoticon agoenks29D_j1grs" emoticon_data="✌"></span>
		<span class="facebook_emoticon agoenks29D_30t6q" emoticon_data="👌"></span>
		<span class="facebook_emoticon agoenks29D_ut8kz" emoticon_data="✋"></span>
		<span class="facebook_emoticon agoenks29D_q2akl" emoticon_data="👐"></span>
		<span class="facebook_emoticon agoenks29D_y6jx1" emoticon_data="💪"></span>
		<span class="facebook_emoticon agoenks29D_a0rbj" emoticon_data="🙏"></span>
		<span class="facebook_emoticon agoenks29D_p5sro" emoticon_data="☝"></span>
		<span class="facebook_emoticon agoenks29D_ujs4z" emoticon_data="👆"></span>
		<span class="facebook_emoticon agoenks29D_g9upk" emoticon_data="👇"></span>
		<span class="facebook_emoticon agoenks29D_e6mwp" emoticon_data="👈"></span>
		<span class="facebook_emoticon agoenks29D_k1uv0" emoticon_data="👉"></span>
		<span class="facebook_emoticon agoenks29D_i89l2" emoticon_data="💅"></span>
		<span class="facebook_emoticon agoenks29D_hfq8g" emoticon_data="👄"></span>
		<span class="facebook_emoticon agoenks29D_3jbvk" emoticon_data="👅"></span>
		<span class="facebook_emoticon agoenks29D_1rfcy" emoticon_data="👀"></span>
		<span class="facebook_emoticon agoenks29D_9nz8e" emoticon_data="🎅"></span>
		<span class="facebook_emoticon agoenks29D_uvkrd" emoticon_data="👰"></span>
		<span class="facebook_emoticon agoenks29D_qcjza" emoticon_data="👙"></span>
		<span class="facebook_emoticon agoenks29D_xfaqp" emoticon_data="💄"></span>
		<span class="facebook_emoticon agoenks29D_2z10h" emoticon_data="💋"></span>
		<span class="facebook_emoticon agoenks29D_b9gfp" emoticon_data="🎩"></span>
		<span class="facebook_emoticon agoenks29D_9pibj" emoticon_data="🎓"></span>
		<span class="facebook_emoticon agoenks29D_57mbx" emoticon_data="👑"></span>
		<span class="facebook_emoticon agoenks29D_eouj4" emoticon_data="🎒"></span>
		<span class="facebook_emoticon agoenks29D_zwc18" emoticon_data="👝"></span>
		<span class="facebook_emoticon agoenks29D_tbo63" emoticon_data="💼"></span>
		<span class="facebook_emoticon agoenks29D_porth" emoticon_data="👓"></span>
		<span class="facebook_emoticon agoenks29D_79uz1" emoticon_data="💍"></span>
		<span class="facebook_emoticon agoenks29D_aeksy" emoticon_data="🌂"></span>
		<span class="facebook_emoticon agoenks29D_p2oid" emoticon_data="👾"></span>
		<span class="facebook_emoticon agoenks29D_j5gu1" emoticon_data="🎃"></span>
		<span class="facebook_emoticon agoenks29D_q3frl" emoticon_data="❤️"></span>
		<span class="facebook_emoticon agoenks29D_nv6or" emoticon_data="💛"></span>
		<span class="facebook_emoticon agoenks29D_9sjng" emoticon_data="💚"></span>
		<span class="facebook_emoticon agoenks29D_cjpx1" emoticon_data="💙"></span>
		<span class="facebook_emoticon agoenks29D_b4aij" emoticon_data="💔"></span>
		<span class="facebook_emoticon agoenks29D_r8epk" emoticon_data="💜"></span>
		<span class="facebook_emoticon agoenks29D_c5hpq" emoticon_data="💕"></span>
		<span class="facebook_emoticon agoenks29D_a03qk" emoticon_data="💓"></span>
		<span class="facebook_emoticon agoenks29D_64f5p" emoticon_data="💞"></span>
		<span class="facebook_emoticon agoenks29D_gayqs" emoticon_data="💗"></span>
		<span class="facebook_emoticon agoenks29D_jrunk" emoticon_data="💘"></span>
		<span class="facebook_emoticon agoenks29D_j1e3b" emoticon_data="💖"></span>
		<span class="facebook_emoticon agoenks29D_prig1" emoticon_data="💝"></span>
		<span class="facebook_emoticon agoenks29D_daz97" emoticon_data="💟"></span>

		// Animals And Nature
		<span class="facebook_emoticon agoenks29D_x5dc7" emoticon_data="🐶"></span>
		<span class="facebook_emoticon agoenks29D_4hjlx" emoticon_data="🐱"></span>
		<span class="facebook_emoticon agoenks29D_ksh62" emoticon_data="🐭"></span>
		<span class="facebook_emoticon agoenks29D_26u4m" emoticon_data="🐹"></span>
		<span class="facebook_emoticon agoenks29D_y2nks" emoticon_data="🐰"></span>
		<span class="facebook_emoticon agoenks29D_i7opj" emoticon_data="🐻"></span>
		<span class="facebook_emoticon agoenks29D_lxmsn" emoticon_data="🐼"></span>
		<span class="facebook_emoticon agoenks29D_85svn" emoticon_data="🐨"></span>
		<span class="facebook_emoticon agoenks29D_reuhw" emoticon_data="🐯"></span>
		<span class="facebook_emoticon agoenks29D_fz7im" emoticon_data="🐮"></span>
		<span class="facebook_emoticon agoenks29D_mo4jx" emoticon_data="🐷"></span>
		<span class="facebook_emoticon agoenks29D_gnup1" emoticon_data="🐽"></span>
		<span class="facebook_emoticon agoenks29D_z2ygj" emoticon_data="🐸"></span>
		<span class="facebook_emoticon agoenks29D_z6lqs" emoticon_data="🐙"></span>
		<span class="facebook_emoticon agoenks29D_aw5cd" emoticon_data="🐵"></span>
		<span class="facebook_emoticon agoenks29D_h91ei" emoticon_data="🙈"></span>
		<span class="facebook_emoticon agoenks29D_tcfl7" emoticon_data="🙉"></span>
		<span class="facebook_emoticon agoenks29D_s548g" emoticon_data="🙊"></span>
		<span class="facebook_emoticon agoenks29D_9lpc2" emoticon_data="🐒"></span>
		<span class="facebook_emoticon agoenks29D_zuhp1" emoticon_data="🐧"></span>
		<span class="facebook_emoticon agoenks29D_wu6d1" emoticon_data="🐦"></span>
		<span class="facebook_emoticon agoenks29D_svxnb" emoticon_data="🐤"></span>
		<span class="facebook_emoticon agoenks29D_o86ci" emoticon_data="🐣"></span>
		<span class="facebook_emoticon agoenks29D_76puv" emoticon_data="🐥"></span>
		<span class="facebook_emoticon agoenks29D_jcuke" emoticon_data="🐺"></span>
		<span class="facebook_emoticon agoenks29D_nwz2d" emoticon_data="🐗"></span>
		<span class="facebook_emoticon agoenks29D_56c29" emoticon_data="🐴"></span>
		<span class="facebook_emoticon agoenks29D_pawkb" emoticon_data="🐝"></span>
		<span class="facebook_emoticon agoenks29D_ondg9" emoticon_data="🐛"></span>
		<span class="facebook_emoticon agoenks29D_u64n1" emoticon_data="🐌"></span>
		<span class="facebook_emoticon agoenks29D_p3510" emoticon_data="🐞"></span>
		<span class="facebook_emoticon agoenks29D_gp3mn" emoticon_data="🐜"></span>
		<span class="facebook_emoticon agoenks29D_tmz0d" emoticon_data="🐍"></span>
		<span class="facebook_emoticon agoenks29D_z8nfo" emoticon_data="🐢"></span>
		<span class="facebook_emoticon agoenks29D_zc2fg" emoticon_data="🐠"></span>
		<span class="facebook_emoticon agoenks29D_6pmsu" emoticon_data="🐟"></span>
		<span class="facebook_emoticon agoenks29D_kq04e" emoticon_data="🐡"></span>
		<span class="facebook_emoticon agoenks29D_6f8to" emoticon_data="🐬"></span>
		<span class="facebook_emoticon agoenks29D_mo19f" emoticon_data="🐳"></span>
		<span class="facebook_emoticon agoenks29D_z25pe" emoticon_data="🐋"></span>
		<span class="facebook_emoticon agoenks29D_a3tq8" emoticon_data="🐊"></span>
		<span class="facebook_emoticon agoenks29D_8j17l" emoticon_data="🐆"></span>
		<span class="facebook_emoticon agoenks29D_6y7w3" emoticon_data="🐅"></span>
		<span class="facebook_emoticon agoenks29D_6it9e" emoticon_data="🐃"></span>
		<span class="facebook_emoticon agoenks29D_8lr1t" emoticon_data="🐂"></span>
		<span class="facebook_emoticon agoenks29D_ydxfr" emoticon_data="🐔"></span>
		<span class="facebook_emoticon agoenks29D_x30bt" emoticon_data="🐄"></span>
		<span class="facebook_emoticon agoenks29D_mvr6y" emoticon_data="🐪"></span>
		<span class="facebook_emoticon agoenks29D_hriap" emoticon_data="🐫"></span>
		<span class="facebook_emoticon agoenks29D_6j9ak" emoticon_data="🐘"></span>
		<span class="facebook_emoticon agoenks29D_6j53n" emoticon_data="🐐"></span>
		<span class="facebook_emoticon agoenks29D_y73j9" emoticon_data="🐏"></span>
		<span class="facebook_emoticon agoenks29D_1frdm" emoticon_data="🐑"></span>
		<span class="facebook_emoticon agoenks29D_rhw71" emoticon_data="🐎"></span>
		<span class="facebook_emoticon agoenks29D_8o3sr" emoticon_data="🐖"></span>
		<span class="facebook_emoticon agoenks29D_l6mr7" emoticon_data="🐀"></span>
		<span class="facebook_emoticon agoenks29D_3jxgb" emoticon_data="🐁"></span>
		<span class="facebook_emoticon agoenks29D_fhjcy" emoticon_data="🐓"></span>
		<span class="facebook_emoticon agoenks29D_wotui" emoticon_data="🐕"></span>
		<span class="facebook_emoticon agoenks29D_kbvx5" emoticon_data="🐩"></span>
		<span class="facebook_emoticon agoenks29D_9ch21" emoticon_data="🐈"></span>
		<span class="facebook_emoticon agoenks29D_k9ap6" emoticon_data="🐇"></span>
		<span class="facebook_emoticon agoenks29D_e1kx3" emoticon_data="🐾"></span>
		<span class="facebook_emoticon agoenks29D_1omlw" emoticon_data="🐉"></span>
		<span class="facebook_emoticon agoenks29D_9bpsy" emoticon_data="🐲"></span>
		<span class="facebook_emoticon agoenks29D_wu5v1" emoticon_data="🌵"></span>
		<span class="facebook_emoticon agoenks29D_rzyth" emoticon_data="🎄"></span>
		<span class="facebook_emoticon agoenks29D_2b7va" emoticon_data="🌲"></span>
		<span class="facebook_emoticon agoenks29D_wmepk" emoticon_data="🌳"></span>
		<span class="facebook_emoticon agoenks29D_09d6g" emoticon_data="🌴"></span>
		<span class="facebook_emoticon agoenks29D_5uw1j" emoticon_data="🌱"></span>
		<span class="facebook_emoticon agoenks29D_kfnat" emoticon_data="🌿"></span>
		<span class="facebook_emoticon agoenks29D_h6c9s" emoticon_data="🍀"></span>
		<span class="facebook_emoticon agoenks29D_0znob" emoticon_data="🍃"></span>
		<span class="facebook_emoticon agoenks29D_k7w18" emoticon_data="🍂"></span>
		<span class="facebook_emoticon agoenks29D_i9scf" emoticon_data="🍁"></span>
		<span class="facebook_emoticon agoenks29D_t4miz" emoticon_data="🌺"></span>
		<span class="facebook_emoticon agoenks29D_mps2n" emoticon_data="🌻"></span>
		<span class="facebook_emoticon agoenks29D_iedoh" emoticon_data="🌹"></span>
		<span class="facebook_emoticon agoenks29D_4yvmq" emoticon_data="🌼"></span>
		<span class="facebook_emoticon agoenks29D_av3qp" emoticon_data="🌷"></span>
		<span class="facebook_emoticon agoenks29D_dovqh" emoticon_data="🌸"></span>
		<span class="facebook_emoticon agoenks29D_g0zci" emoticon_data="🍄"></span>
		<span class="facebook_emoticon agoenks29D_dt76y" emoticon_data="🐚"></span>
		<span class="facebook_emoticon agoenks29D_8g13e" emoticon_data="🌎"></span>
		<span class="facebook_emoticon agoenks29D_vn4b6" emoticon_data="🌚"></span>
		<span class="facebook_emoticon agoenks29D_6rhbq" emoticon_data="🌝"></span>
		<span class="facebook_emoticon agoenks29D_40g1p" emoticon_data="🌛"></span>
		<span class="facebook_emoticon agoenks29D_blx98" emoticon_data="🌜"></span>
		<span class="facebook_emoticon agoenks29D_vwlma" emoticon_data="🌞"></span>
		<span class="facebook_emoticon agoenks29D_blwje" emoticon_data="⭐"></span>
		<span class="facebook_emoticon agoenks29D_7f5or" emoticon_data="🌟"></span>
		<span class="facebook_emoticon agoenks29D_06pqk" emoticon_data="💫"></span>
		<span class="facebook_emoticon agoenks29D_jtsed" emoticon_data="✨"></span>
		<span class="facebook_emoticon agoenks29D_9qnxl" emoticon_data="☀"></span>
		<span class="facebook_emoticon agoenks29D_smr6x" emoticon_data="⛅"></span>
		<span class="facebook_emoticon agoenks29D_emn2x" emoticon_data="☁"></span>
		<span class="facebook_emoticon agoenks29D_hlpfq" emoticon_data="⚡"></span>
		<span class="facebook_emoticon agoenks29D_1sp6i" emoticon_data="🔥"></span>
		<span class="facebook_emoticon agoenks29D_dm2uz" emoticon_data="💥"></span>
		<span class="facebook_emoticon agoenks29D_f1ywc" emoticon_data="❄"></span>
		<span class="facebook_emoticon agoenks29D_rg2eh" emoticon_data="⛄"></span>

		// Objects
		<span class="facebook_emoticon agoenks29D_2eha4" emoticon_data="⚽"></span>
		<span class="facebook_emoticon agoenks29D_ai0e4" emoticon_data="🏀"></span>
		<span class="facebook_emoticon agoenks29D_a9ds8" emoticon_data="🏈"></span>
		<span class="facebook_emoticon agoenks29D_dxbnm" emoticon_data="⚾"></span>
		<span class="facebook_emoticon agoenks29D_sdgnv" emoticon_data="🎾"></span>
		<span class="facebook_emoticon agoenks29D_9kg06" emoticon_data="🏉"></span>
		<span class="facebook_emoticon agoenks29D_fa1pm" emoticon_data="🎱"></span>
		<span class="facebook_emoticon agoenks29D_u1sav" emoticon_data="🎳"></span>
		<span class="facebook_emoticon agoenks29D_hu4iw" emoticon_data="🏆"></span>
		<span class="facebook_emoticon agoenks29D_w6qld" emoticon_data="🎨"></span>
		<span class="facebook_emoticon agoenks29D_jpgce" emoticon_data="🎤"></span>
		<span class="facebook_emoticon agoenks29D_8dfaq" emoticon_data="🎧"></span>
		<span class="facebook_emoticon agoenks29D_4yzif" emoticon_data="🎹"></span>
		<span class="facebook_emoticon agoenks29D_xgzdj" emoticon_data="🎷"></span>
		<span class="facebook_emoticon agoenks29D_842t7" emoticon_data="🎸"></span>
		<span class="facebook_emoticon agoenks29D_fzuro" emoticon_data="🎻"></span>
		<span class="facebook_emoticon agoenks29D_qby46" emoticon_data="🎬"></span>
		<span class="facebook_emoticon agoenks29D_wre28" emoticon_data="🎮"></span>
		<span class="facebook_emoticon agoenks29D_nf327" emoticon_data="🚗"></span>
		<span class="facebook_emoticon agoenks29D_lwk1g" emoticon_data="🚕"></span>
		<span class="facebook_emoticon agoenks29D_1fl9v" emoticon_data="🚇"></span>
		<span class="facebook_emoticon agoenks29D_kamqz" emoticon_data="🚌"></span>
		<span class="facebook_emoticon agoenks29D_dtchq" emoticon_data="🚓"></span>
		<span class="facebook_emoticon agoenks29D_lm93z" emoticon_data="🚑"></span>
		<span class="facebook_emoticon agoenks29D_6l3bq" emoticon_data="🚒"></span>
		<span class="facebook_emoticon agoenks29D_3k4w2" emoticon_data="🚲"></span>
		<span class="facebook_emoticon agoenks29D_3umej" emoticon_data="⚓"></span>
		<span class="facebook_emoticon agoenks29D_iwsvu" emoticon_data="🏁"></span>
		<span class="facebook_emoticon agoenks29D_fy8pu" emoticon_data="🎲"></span>
		<span class="facebook_emoticon agoenks29D_vixy8" emoticon_data="⌚"></span>
		<span class="facebook_emoticon agoenks29D_scgf0" emoticon_data="📱"></span>
		<span class="facebook_emoticon agoenks29D_azkn0" emoticon_data="💻"></span>
		<span class="facebook_emoticon agoenks29D_29kxz" emoticon_data="💽"></span>
		<span class="facebook_emoticon agoenks29D_19gwu" emoticon_data="💾"></span>
		<span class="facebook_emoticon agoenks29D_93dx6" emoticon_data="📷"></span>
		<span class="facebook_emoticon agoenks29D_tlado" emoticon_data="📹"></span>
		<span class="facebook_emoticon agoenks29D_ok6pq" emoticon_data="📞"></span>
		<span class="facebook_emoticon agoenks29D_tgwu1" emoticon_data="📺"></span>
		<span class="facebook_emoticon agoenks29D_gvpq4" emoticon_data="⏰"></span>
		<span class="facebook_emoticon agoenks29D_qbcow" emoticon_data="⌛"></span>
		<span class="facebook_emoticon agoenks29D_4893i" emoticon_data="🔋"></span>
		<span class="facebook_emoticon agoenks29D_20r9n" emoticon_data="💡"></span>
		<span class="facebook_emoticon agoenks29D_brgie" emoticon_data="💵"></span>
		<span class="facebook_emoticon agoenks29D_cjt20" emoticon_data="💶"></span>
		<span class="facebook_emoticon agoenks29D_9ow2c" emoticon_data="💷"></span>
		<span class="facebook_emoticon agoenks29D_xau9s" emoticon_data="💰"></span>
		<span class="facebook_emoticon agoenks29D_184fp" emoticon_data="💳"></span>
		<span class="facebook_emoticon agoenks29D_tpfqj" emoticon_data="💎"></span>
		<span class="facebook_emoticon agoenks29D_t0xsf" emoticon_data="🔧"></span>
		<span class="facebook_emoticon agoenks29D_r21y9" emoticon_data="🔨"></span>
		<span class="facebook_emoticon agoenks29D_dn9za" emoticon_data="🔫"></span>
		<span class="facebook_emoticon agoenks29D_x0ryf" emoticon_data="💣"></span>
		<span class="facebook_emoticon agoenks29D_usbig" emoticon_data="🚬"></span>
		<span class="facebook_emoticon agoenks29D_xozv0" emoticon_data="🚽"></span>
		<span class="facebook_emoticon agoenks29D_nzavr" emoticon_data="🚿"></span>
		<span class="facebook_emoticon agoenks29D_by60i" emoticon_data="🛀"></span>
		<span class="facebook_emoticon agoenks29D_qame3" emoticon_data="🔑"></span>
		<span class="facebook_emoticon agoenks29D_0taqf" emoticon_data="🎈"></span>
		<span class="facebook_emoticon agoenks29D_x5yna" emoticon_data="🎀"></span>
		<span class="facebook_emoticon agoenks29D_5y3pq" emoticon_data="🎁"></span>
		<span class="facebook_emoticon agoenks29D_sbm52" emoticon_data="✉"></span>
		<span class="facebook_emoticon agoenks29D_du1ox" emoticon_data="💌"></span>
		<span class="facebook_emoticon agoenks29D_kdjs4" emoticon_data="📰"></span>
		<span class="facebook_emoticon agoenks29D_cygwl" emoticon_data="📓"></span>
		<span class="facebook_emoticon agoenks29D_d9ikl" emoticon_data="📎"></span>
		<span class="facebook_emoticon agoenks29D_sbd1r" emoticon_data="✂"></span>
		<span class="facebook_emoticon agoenks29D_7v3ez" emoticon_data="📐"></span>
		<span class="facebook_emoticon agoenks29D_9gvhw" emoticon_data="✏"></span>

		// Foods And Drinks
		<span class="facebook_emoticon agoenks29D_bh7qu" emoticon_data="🍏"></span>
		<span class="facebook_emoticon agoenks29D_s6rwm" emoticon_data="🍎"></span>
		<span class="facebook_emoticon agoenks29D_nqiex" emoticon_data="🍐"></span>
		<span class="facebook_emoticon agoenks29D_1cqvm" emoticon_data="🍊"></span>
		<span class="facebook_emoticon agoenks29D_8kubg" emoticon_data="🍋"></span>
		<span class="facebook_emoticon agoenks29D_f2mp0" emoticon_data="🍌"></span>
		<span class="facebook_emoticon agoenks29D_sf527" emoticon_data="🍉"></span>
		<span class="facebook_emoticon agoenks29D_g0yli" emoticon_data="🍇"></span>
		<span class="facebook_emoticon agoenks29D_wrhb9" emoticon_data="🍓"></span>
		<span class="facebook_emoticon agoenks29D_9jqx5" emoticon_data="🍈"></span>
		<span class="facebook_emoticon agoenks29D_ml1sj" emoticon_data="🍒"></span>
		<span class="facebook_emoticon agoenks29D_vebm2" emoticon_data="🍑"></span>
		<span class="facebook_emoticon agoenks29D_wntm2" emoticon_data="🍍"></span>
		<span class="facebook_emoticon agoenks29D_1i380" emoticon_data="🍅"></span>
		<span class="facebook_emoticon agoenks29D_ohbjf" emoticon_data="🍠"></span>
		<span class="facebook_emoticon agoenks29D_53igx" emoticon_data="🍞"></span>
		<span class="facebook_emoticon agoenks29D_rht60" emoticon_data="🍗"></span>
		<span class="facebook_emoticon agoenks29D_s7h3a" emoticon_data="🍖"></span>
		<span class="facebook_emoticon agoenks29D_o0wu7" emoticon_data="🍤"></span>
		<span class="facebook_emoticon agoenks29D_k508g" emoticon_data="🍳"></span>
		<span class="facebook_emoticon agoenks29D_t3kfs" emoticon_data="🍔"></span>
		<span class="facebook_emoticon agoenks29D_x7rny" emoticon_data="🍟"></span>
		<span class="facebook_emoticon agoenks29D_b1x6v" emoticon_data="🍕"></span>
		<span class="facebook_emoticon agoenks29D_3sl2e" emoticon_data="🍝"></span>
		<span class="facebook_emoticon agoenks29D_dy03q" emoticon_data="🍲"></span>
		<span class="facebook_emoticon agoenks29D_a3tki" emoticon_data="🍥"></span>
		<span class="facebook_emoticon agoenks29D_aqx2h" emoticon_data="🍣"></span>
		<span class="facebook_emoticon agoenks29D_z9si4" emoticon_data="🍱"></span>
		<span class="facebook_emoticon agoenks29D_hadcv" emoticon_data="🍛"></span>
		<span class="facebook_emoticon agoenks29D_e4blo" emoticon_data="🍚"></span>
		<span class="facebook_emoticon agoenks29D_75w0v" emoticon_data="🍡"></span>
		<span class="facebook_emoticon agoenks29D_iou6f" emoticon_data="🍧"></span>
		<span class="facebook_emoticon agoenks29D_krnto" emoticon_data="🍨"></span>
		<span class="facebook_emoticon agoenks29D_rvdl3" emoticon_data="🍦"></span>
		<span class="facebook_emoticon agoenks29D_0gt1n" emoticon_data="🍰"></span>
		<span class="facebook_emoticon agoenks29D_2r1hv" emoticon_data="🍯"></span>
		<span class="facebook_emoticon agoenks29D_epfbd" emoticon_data="🎂"></span>
		<span class="facebook_emoticon agoenks29D_216oe" emoticon_data="🍮"></span>
		<span class="facebook_emoticon agoenks29D_z10q8" emoticon_data="🍬"></span>
		<span class="facebook_emoticon agoenks29D_jcsqx" emoticon_data="🍭"></span>
		<span class="facebook_emoticon agoenks29D_r4ymp" emoticon_data="🍫"></span>
		<span class="facebook_emoticon agoenks29D_vfzo2" emoticon_data="🍩"></span>
		<span class="facebook_emoticon agoenks29D_dqrx2" emoticon_data="🍪"></span>
		<span class="facebook_emoticon agoenks29D_sk0px" emoticon_data="🍺"></span>
		<span class="facebook_emoticon agoenks29D_27czp" emoticon_data="🍻"></span>
		<span class="facebook_emoticon agoenks29D_ejm0d" emoticon_data="🍷"></span>
		<span class="facebook_emoticon agoenks29D_h6zyp" emoticon_data="🍸"></span>
		<span class="facebook_emoticon agoenks29D_i1bpn" emoticon_data="🍹"></span>
		<span class="facebook_emoticon agoenks29D_cz6am" emoticon_data="🍵"></span>
		<span class="facebook_emoticon agoenks29D_5jfly" emoticon_data="☕"></span>
		<span class="facebook_emoticon agoenks29D_9nrmo" emoticon_data="🍴"></span>

		// Symbol
		<span class="facebook_emoticon agoenks29D_9glms" emoticon_data="⛎"></span>
		<span class="facebook_emoticon agoenks29D_ye1fz" emoticon_data="♈"></span>
		<span class="facebook_emoticon agoenks29D_7rm6i" emoticon_data="♉"></span>
		<span class="facebook_emoticon agoenks29D_kjdf5" emoticon_data="♊"></span>
		<span class="facebook_emoticon agoenks29D_dzs4j" emoticon_data="♋"></span>
		<span class="facebook_emoticon agoenks29D_76yks" emoticon_data="♌"></span>
		<span class="facebook_emoticon agoenks29D_sr9e4" emoticon_data="♍"></span>
		<span class="facebook_emoticon agoenks29D_7lphi" emoticon_data="♎"></span>
		<span class="facebook_emoticon agoenks29D_0ezq2" emoticon_data="♏"></span>
		<span class="facebook_emoticon agoenks29D_ubhk0" emoticon_data="♐"></span>
		<span class="facebook_emoticon agoenks29D_qhirm" emoticon_data="♑"></span>
		<span class="facebook_emoticon agoenks29D_fpn4h" emoticon_data="♒"></span>
		<span class="facebook_emoticon agoenks29D_wd1pv" emoticon_data="♓"></span>
		<span class="facebook_emoticon agoenks29D_bvatp" emoticon_data="📴"></span>
		<span class="facebook_emoticon agoenks29D_vqbk3" emoticon_data="🆚"></span>
		<span class="facebook_emoticon agoenks29D_nfjhp" emoticon_data="🆘"></span>
		<span class="facebook_emoticon agoenks29D_jmqu7" emoticon_data="⛔"></span>
		<span class="facebook_emoticon agoenks29D_5mye7" emoticon_data="🚫"></span>
		<span class="facebook_emoticon agoenks29D_hrbeu" emoticon_data="❌"></span>
		<span class="facebook_emoticon agoenks29D_c48ql" emoticon_data="⭕"></span>
		<span class="facebook_emoticon agoenks29D_e478m" emoticon_data="💢"></span>
		<span class="facebook_emoticon agoenks29D_wsdq6" emoticon_data="❗️"></span>
		<span class="facebook_emoticon agoenks29D_ti7fr" emoticon_data="❓"></span>
		<span class="facebook_emoticon agoenks29D_ncohv" emoticon_data="⚠"></span>
		<span class="facebook_emoticon agoenks29D_6ol13" emoticon_data="❎"></span>
		<span class="facebook_emoticon agoenks29D_r4m5g" emoticon_data="✅"></span>
		<span class="facebook_emoticon agoenks29D_al24v" emoticon_data="🚭"></span>
		<span class="facebook_emoticon agoenks29D_1muex" emoticon_data="🚾"></span>
		<span class="facebook_emoticon agoenks29D_b0mt5" emoticon_data="🆗"></span>
		<span class="facebook_emoticon agoenks29D_jpw57" emoticon_data="🆒"></span>
		<span class="facebook_emoticon agoenks29D_gv6d3" emoticon_data="🆕"></span>
		<span class="facebook_emoticon agoenks29D_5rsgf" emoticon_data="🆓"></span>
		<span class="facebook_emoticon agoenks29D_ajxdp" emoticon_data="🆙"></span>
		<span class="facebook_emoticon agoenks29D_wz0fu" emoticon_data="➡"></span>
		<span class="facebook_emoticon agoenks29D_tbfgc" emoticon_data="⬅"></span>
		<span class="facebook_emoticon agoenks29D_3fz10" emoticon_data="⬆"></span>
		<span class="facebook_emoticon agoenks29D_ulwcg" emoticon_data="⬇"></span>
		<span class="facebook_emoticon agoenks29D_8ohr1" emoticon_data="↗"></span>
		<span class="facebook_emoticon agoenks29D_q4has" emoticon_data="↘"></span>
		<span class="facebook_emoticon agoenks29D_qvr1w" emoticon_data="↙"></span>
		<span class="facebook_emoticon agoenks29D_p50b1" emoticon_data="↖"></span>
		<span class="facebook_emoticon agoenks29D_b7cr8" emoticon_data="☑"></span>
		<span class="facebook_emoticon agoenks29D_seiom" emoticon_data="💲"></span>
		<span class="facebook_emoticon agoenks29D_i4om6" emoticon_data="©️"></span>
		<span class="facebook_emoticon agoenks29D_jog0a" emoticon_data="®️"></span>
		<span class="facebook_emoticon agoenks29D_lg8pn" emoticon_data="™️"></span>
		<span class="facebook_emoticon agoenks29D_8y7gi" emoticon_data="🔇"></span>
		<span class="facebook_emoticon agoenks29D_3kip7" emoticon_data="♠"></span>
		<span class="facebook_emoticon agoenks29D_ljsw5" emoticon_data="♣"></span>
		<span class="facebook_emoticon agoenks29D_m7xil" emoticon_data="♥"></span>
		<span class="facebook_emoticon agoenks29D_5a1hw" emoticon_data="♦"></span>

		// Flag
		<span class="facebook_emoticon agoenks29D_rlnav" emoticon_data="🇺🇸"></span>
		<span class="facebook_emoticon agoenks29D_yge9w" emoticon_data="🇦🇪"></span>
		<span class="facebook_emoticon agoenks29D_bes2j" emoticon_data="🇻🇳"></span>
		<span class="facebook_emoticon agoenks29D_k1pg9" emoticon_data="🇦🇹"></span>
		<span class="facebook_emoticon agoenks29D_sxaof" emoticon_data="🇦🇺"></span>
		<span class="facebook_emoticon agoenks29D_7vu1k" emoticon_data="🇿🇦"></span>
		<span class="facebook_emoticon agoenks29D_sd0wy" emoticon_data="🇧🇪"></span>
		<span class="facebook_emoticon agoenks29D_yfw89" emoticon_data="🇧🇷"></span>
		<span class="facebook_emoticon agoenks29D_7o5su" emoticon_data="🇨🇦"></span>
		<span class="facebook_emoticon agoenks29D_tk1ow" emoticon_data="🇨🇭"></span>
		<span class="facebook_emoticon agoenks29D_dgaj5" emoticon_data="🇨🇱"></span>
		<span class="facebook_emoticon agoenks29D_kao7d" emoticon_data="🇨🇴"></span>
		<span class="facebook_emoticon agoenks29D_wm36b" emoticon_data="🇩🇪"></span>
		<span class="facebook_emoticon agoenks29D_etn3c" emoticon_data="🇩🇰"></span>
		<span class="facebook_emoticon agoenks29D_t8oiz" emoticon_data="🇪🇸"></span>
		<span class="facebook_emoticon agoenks29D_1imu7" emoticon_data="🇫🇮"></span>
		<span class="facebook_emoticon agoenks29D_qzso4" emoticon_data="🇫🇷"></span>
		<span class="facebook_emoticon agoenks29D_s3r9x" emoticon_data="🇬🇧"></span>
		<span class="facebook_emoticon agoenks29D_rz42m" emoticon_data="🇮🇩"></span>
		<span class="facebook_emoticon agoenks29D_yz135" emoticon_data="🇮🇪"></span>
		<span class="facebook_emoticon agoenks29D_3fynz" emoticon_data="🇮🇱"></span>
		<span class="facebook_emoticon agoenks29D_du93a" emoticon_data="🇮🇳"></span>
		<span class="facebook_emoticon agoenks29D_fv5d7" emoticon_data="🇮🇹"></span>
		<span class="facebook_emoticon agoenks29D_79kbv" emoticon_data="🇯🇵"></span>
		<span class="facebook_emoticon agoenks29D_mdcp6" emoticon_data="🇰🇷"></span>
		<span class="facebook_emoticon agoenks29D_wy9s2" emoticon_data="🇳🇱"></span>
		<span class="facebook_emoticon agoenks29D_fkc0g" emoticon_data="🇳🇴"></span>
		<span class="facebook_emoticon agoenks29D_wdzyv" emoticon_data="🇳🇿"></span>
		<span class="facebook_emoticon agoenks29D_wc6it" emoticon_data="🇵🇭"></span>
		<span class="facebook_emoticon agoenks29D_w645r" emoticon_data="🇵🇱"></span>
		<span class="facebook_emoticon agoenks29D_racnj" emoticon_data="🇵🇹"></span>
		<span class="facebook_emoticon agoenks29D_7f3k1" emoticon_data="🇷🇺"></span>
		<span class="facebook_emoticon agoenks29D_aczqw" emoticon_data="🇸🇪"></span>
		<span class="facebook_emoticon agoenks29D_3grt4" emoticon_data="🇹🇷"></span>
    ';
    return $emoticon_list;
}